# Removemos 'worker_processes auto' para evitar conflitos em instâncias pequenas do Cloud Run
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logs formatados para o Google Cloud Logging
    access_log /dev/stdout;
    error_log /dev/stderr;

    sendfile        on;
    keepalive_timeout  65;

    server {
        # Porta padrão do Cloud Run
        listen 8080;
        server_name localhost;

        # Onde o Angular estará (dentro do container)
        root /usr/share/nginx/html;
        index index.html;

        # Suporte para rotas do Angular (evita 404 no Refresh)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Cache Control para o index.html (Sempre buscar versão nova)
        location = /index.html {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires 0;
        }

        # Cache agressivo para assets (Imagens, JS, CSS com hash)
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, max-age=31536000, immutable";
            access_log off;
            try_files $uri =404;
        }

        # Página de erro simples
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}